apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-backend
  labels:
    app: echo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-backend
  template:
    metadata:
      labels:
        app: echo-backend
    spec:
      containers:
      - name: echo-backend
        image: echo-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000