apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  type: LoadBalancer
  selector:
    app: echo-backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    nodePort: 30000